apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: simple-monitoring
    app.kubernetes.io/component: monitoring
  name: simple-monitoring
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: simple-monitoring
